openapi: 3.0.3
info:
  title: API de Carts
  version: 1.0.0
  description: Documentación de la API para la gestión de carritos de compra.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: ID único del carrito
          example: "60c72b2f9b1e8e001c8e4b8a"
        user_id:
          type: string
          description: ID del usuario
          example: "60c72b2f9b1e8e001c8e4b8c"
        products:
          type: array
          description: Lista de productos en el carrito
          items:
            type: object
            properties:
              product_id:
                type: string
                description: ID del producto
                example: "686ecc03efa4f55fd7e433ae"
              quantity:
                type: integer
                description: Cantidad de ese producto
                example: 2
      description: Modelo de carrito
      example:
        _id: "60c72b2f9b1e8e001c8e4b8a"
        user_id: "60c72b2f9b1e8e001c8e4b8c"
        products:
          - product_id: "60c72b2f9b1e8e001c8e4b8b"
            quantity: 2
    Error:
      type: object
      properties:
        message:
          type: string
      example:
        message: "Error interno del servidor"
    Success:
      type: object
      properties:
        message:
          type: string
          example: "Operación exitosa"
        data:
          type: object
          additionalProperties: true
  responses:
    UnauthorizedError:
      description: No autorizado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "No autorizado"
    Forbidden:
      description: Acceso prohibido
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "Acceso prohibido"
    NotFound:
      description: Recurso no encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "Carrito no encontrado"
    InternalServerError:
      description: Error interno del servidor
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "Error interno del servidor"
    Success:
      description: Operación exitosa
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Success'
paths:
  /api/carts/clear:
    delete:
      summary: Limpia el carrito del usuario autenticado
      tags:
        - Carts
      security:
        - bearerAuth: []
      responses:
        200:
          description: Carrito limpiado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        401:
          description: Usuario no autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/responses/UnauthorizedError'
        404:
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/responses/NotFound'
        500:
          description: Error del lado del servidor al limpiar el carrito
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InternalServerError'
  /api/carts/mycart:
    get:
      summary: Obtiene el carrito del usuario autenticado
      tags:
        - Carts
      security:
        - bearerAuth: []
      responses:
        200:
          description: Carrito obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        401:
          description: Usuario no autenticado
          content:
            application/json:
              schema:
                $ref: '#/components/responses/UnauthorizedError'
        404:
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/responses/NotFound'
        500:
          description: Error del lado del servidor al obtener el carrito
          content:
            application/json:
              schema:
                $ref: '#/components/responses/InternalServerError'
  /api/carts/add/product:
    post:
      summary: Agrega un producto al carrito del usuario autenticado
      tags:
        - Carts
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pid:
                  type: string
                  description: ID del producto a agregar
                  example: "684a4415cccdb7cfcdf2cb15"
                cid:
                  type: string
                  description: ID del carrito al que se agregará el producto
                  example: "686ecc03efa4f55fd7e433ae"
      responses:
        201:
          description: Producto agregado exitosamente al carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        400:
          description: Datos inválidos para agregar el producto al carrito
          content:
            application/json:
              schema:
                $ref: '#/components/responses/error400'
        500:
          description: Error del lado del servidor al agregar el producto al carrito
          content:
            application/json:
              schema:
                $ref: '#/components/responses/error500'